
title: "Shruti Singh – PhD Portfolio"
description: "PhD Portfolio | Safe RL, ML, CV, Human-AI"
# theme: minima
remote_theme: hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
